### PR TITLE
Diagram refactor

### LINKED ISSUE #21: Consider restructing `Notification service` calls, wouldn't it be better to not have the service communicating with frontend and have this part of the business logic embedded in `Rest API`?

### LINKED ISSUE #23: Typo: `storeS messages IN database`, not `store messages TO database`

### LINKED ISSUE #24: Use 3rd person singular form of verbs - requests, gets...

### PR DESCRIPTION
**Pull request by damodarak**
Resolves #21 
Resolves #23
Resolves #24

### CODE REVIEW

**Comment by michael-sevcik** [comment]
I restructured the more complicated graphs to keep all the relationships visible, if you would rather keep the autolayout on all graphs, feel free to change it back.

image

I fixed this link label, I believe "Sends processed data" label was the indended one.

Finally, I would like to sugest **for discussion** labeling the `Auth Service`  by colour as foreign service (SW system) as is done in example from lecture:
image

**Review by michael-sevcik — COMMENTED** [review]
Looks good to me, after we make a decision on the suggestion above, you have my approval.

**Comment by michael-sevcik** [comment]
Btw. we could also resolve the #20 issue here

**Comment by TomasBoda** [comment]
@michael-sevcik added your suggestion, changed the colour scheme of the entire diagram to make more sense. As far as I'm concerned, we can merge. What about @sezikpepa @notSnuffy @matejsubrt ?

**Comment by notSnuffy** [comment]
Looks good, but I think Message Controller has no arrow going into it. So it is basically unreachable. Also I feel like the WebSocket should have arrows going both ways? Since WebSockets are usually used for two-way communication but maybe I don't understand it enough.

**Comment by TomasBoda** [comment]
Fixed the `message_controller` arrows, added `web_socket_controller` arrows. I think we are ready to merge. @michael-sevcik what do you think?

**Pull request merged**
